language: python
notification:
    email: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

matrix:
    allow_failures:
        - python: "pypy"

before_install:
  - pushd .
  - travis_retry sudo apt-get update -qq
  - travis_retry pip install Cython
  - travis_retry sudo apt-get install -y curl erlang python-dev
  - travis_retry git clone https://github.com/discoproject/disco.git /tmp/disco
  - cd /tmp/disco && git checkout develop && sudo make install
  - cd lib && pip install .
  - popd

install:
  - travis_retry pip install mock
  - sudo bash ./bootstrap.sh

script: nosetests test/
